using EffectsSpace.Animation;
using EffectsSpace.Core;
using EffectsSpace.Documents;
using EffectsSpace.Editing;

var passed = 0; var failed = 0;
void Test(string name, Action test) { try { test(); passed++; Console.WriteLine("PASS " + name); } catch (Exception e) { failed++; Console.Error.WriteLine($"FAIL {name}: {e}"); } }
void Check(bool condition) { if (!condition) throw new Exception("Assertion failed."); }
void Near(double a, double b, double epsilon = 1e-6) { if (!double.IsFinite(b) || Math.Abs(a - b) > epsilon) throw new Exception($"Expected {a}, got {b}"); }
void Throws(Action action) { try { action(); } catch { return; } throw new Exception("Expected failure."); }
EditorSession Session() { var s = new EditorSession(MotionProject.Empty()); s.AddLayer(LayerKind.Rectangle); return s; }
Channel Curve(params (double Time, double Value)[] values) { var c = new Channel(); foreach (var (time, value) in values) c.SetKey(time, value, Interpolation.Linear); return c; }

Test("all transform channels retain stable paths", () => { var s = Session(); Check(LayerChannels.Enumerate(s.Primary!).Select(p => p.Path).SequenceEqual(new[] { "X", "Y", "AnchorX", "AnchorY", "ScaleX", "ScaleY", "Rotation", "Opacity" })); });
Test("effect channel addresses survive stack reordering", () => { var s = Session(); var a = EffectCatalog.Create(EffectKind.Glow); var b = EffectCatalog.Create(EffectKind.GaussianBlur); s.Primary!.Effects = [a,b]; var path = LayerChannels.EffectPath(a.Id,"Radius"); var c = LayerChannels.Get(s.Primary,path); s.Primary.Effects.Reverse(); Check(ReferenceEquals(c,LayerChannels.Get(s.Primary,path))); });
Test("same effect instances have distinct addresses", () => { var s = Session(); s.Primary!.Effects = [EffectCatalog.Create(EffectKind.Glow), EffectCatalog.Create(EffectKind.Glow)]; var tracks = LayerChannels.Enumerate(s.Primary).Where(p=>p.Parameter=="Radius").ToArray(); Check(tracks[0].Path != tracks[1].Path); Check(tracks[1].EffectOccurrence == 1); });
Test("multikey selection across channels", () => { var s = Session(); var l = s.Primary!; l.Transform.X = Curve((0,0),(1,100)); l.Transform.Y = Curve((0,20),(2,40)); s.SelectKeys([l.Transform.X.Keys[0].Id,l.Transform.Y.Keys[1].Id]); Check(s.SelectedKeyIds.Count == 2); Check(s.SelectedKeys().Length == 2); });
Test("legacy single key setter replaces selection", () => { var s = Session(); var c = s.Primary!.Transform.X = Curve((0,0),(1,10)); s.SelectKeys(c.Keys.Select(k=>k.Id)); s.SelectedKeyId = c.Keys[0].Id; Check(s.SelectedKeyIds.Count == 1); });
Test("key selection creates no history revision", () => { var s = Session(); var c = s.Primary!.Transform.X = Curve((0,0),(1,10)); var rev = s.Revision; s.SelectKeys(c.Keys.Select(k=>k.Id)); s.ToggleKey(c.Keys[0].Id); Near(rev,s.Revision); Check(s.SelectedKeyIds.Count==1); });
Test("clipboard retains relative time and easing without sharing mutable keys", () => { var s = Session(); var c = s.Primary!.Transform.X = Curve((1,10),(3,30)); c.Keys[0].Interpolation=Interpolation.Bezier; c.Keys[0].Y1=-.5; s.SelectKeys(c.Keys.Select(k=>k.Id)); s.CopyKeys(); c.Keys[0].Value=99; var track=s.KeyClipboard!.Tracks[0]; Near(10,track.Keys[0].Value); Near(0,track.Keys[0].Time); Near(2,track.Keys[1].Time); Near(-.5,track.Keys[0].Y1); });
Test("paste creates unique ids and selects the pasted keys", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,10),(1,20)); var ids=c.Keys.Select(k=>k.Id).ToHashSet(); s.SelectKeys(ids); s.CopyKeys(); s.SetTime(3); s.PasteKeys(); Check(c.Keys.Count==4); Check(s.SelectedKeyIds.Count==2); Check(!s.SelectedKeyIds.Any(ids.Contains)); Near(3,s.SelectedKeys().Min(t=>t.Key.Time)); ProjectValidator.Validate(s.Project); });
Test("paste replaces existing destination key once", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,10),(1,20)); s.SelectKeys([c.Keys[0].Id]); s.CopyKeys(); s.SetTime(1); s.PasteKeys(); Check(c.Keys.Count==2); Near(10,c.Keys[1].Value); });
Test("paste boundary rejects whole operation", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,10),(2,20)); s.SelectKeys(c.Keys.Select(k=>k.Id)); s.CopyKeys(); s.SetTime(7); var before=ProjectJson.Save(s.Project); Throws(()=>s.PasteKeys()); Check(ProjectJson.Save(s.Project)==before && !s.IsEditing); });
Test("paste to a different property is explicit", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,10),(1,20)); s.SelectKeys(c.Keys.Select(k=>k.Id)); s.CopyKeys(); s.Property="Y"; s.SetTime(2); s.PasteKeys(true); Check(s.Primary!.Transform.Y.Keys.Count==2); Near(2,s.Primary.Transform.Y.Keys[0].Time); });
Test("paste scalar key clamps to destination semantic range", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,200)); s.SelectKeys([c.Keys[0].Id]); s.CopyKeys(); s.Property="Opacity"; s.PasteKeys(true); Near(100,s.Primary!.Transform.Opacity.Keys[0].Value); });
Test("effect paste resolves kind and occurrence not source identifier", () => { var s=Session(); var source=s.Primary!; source.Effects.Add(EffectCatalog.Create(EffectKind.Glow)); var c=source.Effects[0].Parameters["Radius"]; c.SetKey(0,14); c.SetKey(1,45); s.SelectKeys(c.Keys.Select(k=>k.Id)); s.CopyKeys(); var target=s.AddLayer(LayerKind.Ellipse); target.Effects.Add(EffectCatalog.Create(EffectKind.Glow)); s.SetTime(2); s.PasteKeys(); var dest=target.Effects[0].Parameters["Radius"]; Check(dest.Keys.Count==2); Near(14,dest.Keys[0].Value); Near(2,dest.Keys[0].Time); });
Test("missing effect paste fails without a partial write", () => { var s=Session(); var l=s.Primary!; l.Effects.Add(EffectCatalog.Create(EffectKind.Glow)); l.Transform.X.SetKey(0,12); var c=l.Effects[0].Parameters["Radius"]; c.SetKey(0,15); s.SelectKeys([l.Transform.X.Keys[0].Id,c.Keys[0].Id]); s.CopyKeys(); s.AddLayer(LayerKind.Ellipse); var before=ProjectJson.Save(s.Project); Throws(()=>s.PasteKeys()); Check(before==ProjectJson.Save(s.Project)); });
Test("multi-layer paste maps selected stacking order", () => { var s=Session(); var a=s.Primary!; var b=s.AddLayer(LayerKind.Ellipse); a.Transform.X=Curve((0,11)); b.Transform.X=Curve((0,22)); s.SelectKeys([a.Transform.X.Keys[0].Id,b.Transform.X.Keys[0].Id]); s.CopyKeys(); var x=s.AddLayer(LayerKind.Text); var y=s.AddLayer(LayerKind.Rectangle); s.Select(y.Id); s.SelectedIds.Add(x.Id); s.SetTime(2); s.PasteKeys(); Near(22,y.Transform.X.Keys[0].Value); Near(11,x.Transform.X.Keys[0].Value); });
Test("mismatched layer counts fail explicitly", () => { var s=Session(); var a=s.Primary!; var b=s.AddLayer(LayerKind.Text); a.Transform.X.SetKey(0,10); b.Transform.X.SetKey(0,20); s.SelectKeys([a.Transform.X.Keys[0].Id,b.Transform.X.Keys[0].Id]); s.CopyKeys(); s.Select(a.Id); Throws(()=>s.PasteKeys()); });
Test("frame-rate downsampling collision is rejected", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,10),(1d/60,20)); s.SelectKeys(c.Keys.Select(k=>k.Id)); s.CopyKeys(); s.Composition.FrameRate=new(24,1); s.SetTime(3); Throws(()=>s.PasteKeys()); Check(c.Keys.Count==2); });
Test("drag applies one shared delta and preserves spacing", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((1,10),(2,20),(4,40)); s.SelectKeys(c.Keys.Take(2).Select(k=>k.Id)); using var edit=new KeyframeMove(s); Check(edit.TryPreview(.5,3)); Near(1.5,c.Keys[0].Time); Near(2.5,c.Keys[1].Time); Near(13,c.Keys[0].Value); Near(23,c.Keys[1].Value); edit.Commit(); });
Test("collision rejects every channel in a drag", () => { var s=Session(); var l=s.Primary!; l.Transform.X=Curve((0,0),(2,20)); l.Transform.Y=Curve((0,1),(4,4)); s.SelectKeys([l.Transform.X.Keys[0].Id,l.Transform.Y.Keys[0].Id]); using var edit=new KeyframeMove(s); Check(edit.TryPreview(1,0)); Check(!edit.TryPreview(2,9)); Near(1,l.Transform.X.Keys[0].Time); Near(1,l.Transform.Y.Keys[0].Time); Near(0,l.Transform.X.Keys[0].Value); edit.Commit(); });
Test("drag cancellation restores document and multikey selection", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((1,10),(2,20)); s.SelectKeys(c.Keys.Select(k=>k.Id)); var before=ProjectJson.Save(s.Project); using(var edit=new KeyframeMove(s)) Check(edit.TryPreview(2,10)); Check(before==ProjectJson.Save(s.Project)); Check(s.SelectedKeyIds.Count==2 && !s.IsEditing); });
Test("drag undo and redo restore multikey selection", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((1,10),(2,20)); var ids=c.Keys.Select(k=>k.Id).ToArray(); s.SelectKeys(ids); using(var edit=new KeyframeMove(s)) { Check(edit.TryPreview(.5,2)); edit.Commit(); } s.Undo(); Near(1,s.Primary!.Transform.X.Keys[0].Time); Check(s.SelectedKeyIds.SetEquals(ids)); s.Redo(); Near(1.5,s.Primary.Transform.X.Keys[0].Time); Check(s.SelectedKeyIds.SetEquals(ids)); });
Test("group drag clamps at the composition start without collapsing keys", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((1,10),(2,20)); s.SelectKeys(c.Keys.Select(k=>k.Id)); using var edit=new KeyframeMove(s); Check(edit.TryPreview(-20,0)); Near(0,c.Keys[0].Time); Near(1,c.Keys[1].Time); edit.Commit(); });
Test("effect ranges constrain shared value drag", () => { var s=Session(); var l=s.Primary!; l.Effects.Add(EffectCatalog.Create(EffectKind.GaussianBlur)); var c=l.Effects[0].Parameters["Radius"]; c.SetKey(0,10); c.SetKey(1,100); s.SelectKeys(c.Keys.Select(k=>k.Id)); using var edit=new KeyframeMove(s); Check(edit.TryPreview(0,100)); Near(38,c.Keys[0].Value); Near(128,c.Keys[1].Value); edit.Commit(); });
Test("locked selected keys are not mutated", () => { var s=Session(); var a=s.Primary!; var b=s.AddLayer(LayerKind.Ellipse); a.Transform.X.SetKey(1,10); b.Transform.X.SetKey(1,20); b.Locked=true; s.SelectKeys([a.Transform.X.Keys[0].Id,b.Transform.X.Keys[0].Id]); s.NudgeKeys(1); Near(1+1d/30,a.Transform.X.Keys[0].Time); Near(1,b.Transform.X.Keys[0].Time); });
Test("cut refuses locked keys", () => { var s=Session(); var l=s.Primary!; l.Transform.X.SetKey(0,10); s.SelectKeys([l.Transform.X.Keys[0].Id]); l.Locked=true; Throws(()=>s.CutKeys()); Check(l.Transform.X.Keys.Count==1); });
Test("deleting every key preserves the current evaluated value", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,10),(2,30)); s.SetTime(1); s.SelectKeys(c.Keys.Select(k=>k.Id)); s.DeleteKeys(); Check(c.Keys.Count==0); Near(20,c.Value); s.Undo(); Check(s.Primary!.Transform.X.Keys.Count==2 && s.SelectedKeyIds.Count==2); });
Test("key navigation is frame-aware and stable at ends", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((1,10),(3,30)); s.SetTime(2); s.NavigateKey(-1); Near(1,s.Time); s.NavigateKey(1); Near(3,s.Time); s.NavigateKey(1); Near(3,s.Time); });
Test("easy ease only changes relevant temporal endpoints", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,0),(1,10),(2,20)); s.SelectKeys([c.Keys[1].Id]); s.EaseKeys(EaseDirection.Both); Near(1d/3,c.Keys[0].Y1); Near(1,c.Keys[0].Y2); Near(0,c.Keys[1].Y1); Near(2d/3,c.Keys[1].Y2); });
Test("ease in leaves outgoing interpolation alone", () => { var s=Session(); var c=s.Primary!.Transform.X=Curve((0,0),(1,10),(2,20)); s.SelectKeys([c.Keys[1].Id]); s.EaseKeys(EaseDirection.In); Check(c.Keys[1].Interpolation==Interpolation.Linear); Near(1,c.Keys[0].Y2); });
Test("velocity of linear curve uses seconds not normalized progress", () => { var c=Curve((1,10),(3,50)); Check(CurveVelocity.TryEvaluate(c,2,out var v)); Near(20,v); });
Test("velocity before and after animation is zero", () => { var c=Curve((1,10),(3,50)); Check(CurveVelocity.TryEvaluate(c,0,out var a)); Check(CurveVelocity.TryEvaluate(c,4,out var b)); Near(0,a); Near(0,b); });
Test("Bezier velocity has zero eased endpoint speeds", () => { var c=Curve((0,0),(2,100)); c.Keys[0].Interpolation=Interpolation.Bezier; c.Keys[0].Y1=0;c.Keys[0].Y2=1; Check(CurveVelocity.TryEvaluate(c,0,out var a)); Check(CurveVelocity.TryEvaluate(c,2,out var b)); Near(0,a);Near(0,b); Check(CurveVelocity.TryEvaluate(c,1,out var mid)); Near(75,mid); });
Test("Bezier velocity agrees with numerical derivative", () => { var c=Curve((0,50),(3,-10)); var k=c.Keys[0]; k.Interpolation=Interpolation.Bezier;k.X1=.1;k.X2=.8;k.Y1=-.3;k.Y2=1.2; for(var i=1;i<30;i++){var t=i/10d;const double h=1e-5;var expected=(CurveEvaluator.Evaluate(c,t+h)-CurveEvaluator.Evaluate(c,t-h))/(2*h); Check(CurveVelocity.TryEvaluate(c,t,out var actual));Near(expected,actual,.001);} });
Test("degenerate equal Bezier derivatives use finite limit", () => { var c=Curve((0,0),(1,10)); var k=c.Keys[0];k.Interpolation=Interpolation.Bezier;k.X1=k.Y1=0;k.X2=k.Y2=0;Check(CurveVelocity.TryEvaluate(c,0,out var v));Near(10,v); });
Test("infinite endpoint velocity is a graph gap", () => { var c=Curve((0,0),(1,10));var k=c.Keys[0];k.Interpolation=Interpolation.Bezier;k.X1=0;k.Y1=.5;Check(!CurveVelocity.TryEvaluate(c,0,out _)); });
Test("hold discontinuities are graph gaps", () => { var c=Curve((0,0),(1,10),(2,20));c.Keys[0].Interpolation=Interpolation.Hold;Check(CurveVelocity.TryEvaluate(c,.5,out var v));Near(0,v);Check(!CurveVelocity.TryEvaluate(c,1,out _)); });
Test("expression velocity is a finite-difference estimate", () => { var c=new Channel{Expression="sin(time * 2)"};Check(CurveVelocity.TryEvaluate(c,.4,out var v));Near(2*Math.Cos(.8),v,.0001); });
Test("replacing projects clears stale effect property and selection", () => { var s=Session();var l=s.Primary!;l.Effects.Add(EffectCatalog.Create(EffectKind.Glow));var c=l.Effects[0].Parameters["Radius"];c.SetKey(0,10);s.SelectKeys([c.Keys[0].Id]);s.Replace(MotionProject.Empty());Check(s.Property=="X" && s.SelectedKeyIds.Count==0); });

Console.WriteLine($"\n{passed} animation editing tests passed; {failed} failed.");
return failed == 0 ? 0 : 1;
